# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc84d8de773babbc59d849ce5c5b67f3cc6067cbd94694c53ced82478e417be68c85b84b8f9175e7d0e9fd74958beff181277c1c5f02a0fae91208a9fc438993

test:
  secret_key_base: 9b3908d50d5390aaa7865c23295660a11f8c29702673777855886173c8da8630f5c550afaa50a547efc132f807fbee6792847be2c4549901da465eedd0544ace

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
